#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'numPlayers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY scores
#
import collections

def numPlayers(k, scores):
    ## Version 1
    # l = len(scores)
    # if len(scores) > 0:
    #     lowest = scores[0]
    # else:
    #     lowest = -1
    # rank = []
    # numOfPlayers = 0
    # if len(rank) == 1:
    #     return numOfPlayers
    
    # for i in range(1, len(scores)):
    #     if scores[i] < lowest:
    #         lowest = scores[i]
    
    # count = 0
    # newScores = []
    # for s in scores:
    #     if s == lowest:
    #         count += 1
        
    #     if s > lowest:
    #         newScores.append(s)
    
    # for n in range(count):
    #     rank.append(len(rank) + 1)
    
    # countPlayers = 0
    # for r in rank:
    #     if r >= k:
    #         countPlayers += 1
            
    # for i in range(len(scores)):
    #     lowest = min(lowest, numPlayers(k, newScores))
    
    ## Version 2
    count = collections.Counter(scores)
    ans, cur_rank = 0, 1
    for m, l in sorted(count.items(), reverse=True):
        if cur_rank > k:
            break
        ans += l
        cur_rank += l
    
    return ans
if __name__ == '__main__':
